# [Info]
site_name: RyuYal's Learning Journey # 左上角标题
site_url: https://ryuyal.github.io
site_author: RyuYal
site_description: RyuYal's Learning Journey

# [Navigtion]
nav:
  - CS学习记录: #横向导航栏
    - CS/index.md 
    # - Linux:
    #   - Linux讲座: CS/Linux/linux.md
    #   - 命令行入门精简版: CS/Linux/commands-concise.md
    - 实用工具:
      - MarkDown: CS/Tools/markd.md
      - Git: CS/Tools/git.md
      - GitHub: CS/Tools/github.md
      - IDEA: CS/Tools/idea.md
      - CLion: CS/Tools/clion.md
      - VSCode: CS/Tools/vscode.md
      - 科研相关: CS/Tools/research.md
    
    - 数据结构与算法:
      - 数据结构与算法基础-青岛大学王卓老师: CS/Algos/ds_wangzhuo.md
      - LeetCode: CS/Algos/lc_recommend.md
    
    - 操作系统:
      - CS/OS/operating.md

    - 计算机网络:
      - CS/CSNetwork/csn.md
    
  - 英语:
    - ENGLISH/index.md
  
  - 西班牙语:
    - SPANISH/index.md

  - 兴趣爱好:
    - HOBBY/index.md
    - 网球: 
      - 网球规则: HOBBY/Tennis/tennis-rules.md
      - WTA:
        - HOBBY/Tennis/wta.md
        - 莱巴金娜: HOBBY/Tennis/wta/rybakina.md
      - ATP:
        - HOBBY/Tennis/atp.md
        - 三巨头: HOBBY/Tennis/atp/bigthree.md
      - 趣味小知识: HOBBY/Tennis/funny.md
    - 足球:
      - 足球规则: HOBBY/Soccer/soccer-rules.md

  - 关于我:
    - ME/index.md
    - 个人履历: ME/cv-full.md
    # - 支持作者: ME/support.md

  - 网站:
    - WEBSITE/index.md # 访客打开网站第一个看到的是 docs/index.md（会报错 The following pages exist in the docs directory, but are not included in the "nav" configuration: index.md 不要紧）  如果访客之后想要重新看到这个界面  可以在 docs/WEBSITE/index.md 找到
    - 网站构建: WEBSITE/build.md
    # - 文章编写帮助: WEBSITE/help.md
    # - 测试文档: WEBSITE/test.md

# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 顶部栏颜色
      # primary: light blue
      # primary: cyan

      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类（导航栏）
    - navigation.tabs.sticky # 使用Tab来进行分类，并且导航栏固定
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/ryuyal/ryuyal.github.io # 右上角点击跳转的链接
repo_name: ryuyal.github.io # 右上角的名字
## [bottom-left corner]
copyright: RyuYal CC0-1.0-Universal # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/github
      link: https://github.com/ryuyal
      name: GitHub | RyuYal

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要

extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols